### ISSUE TITLE
Discussões a serem implementadas no trabalho

### ISSUE THREAD

**Issue by flavio-carvalho** [Francimary/Algoritmos#1]
Os alunos devem buscar responder aos seguintes questionamentos e alcançar os seguintes resultados:
    - Qual o tempo de execução "teórico" de cada algoritmo no pior caso, no caso médio e no melhor caso?
    - Quais as entradas que evidenciam/realizam o melhor caso e o pior caso?
    - O comportamento experimental evidencia as análise teóricas?
    - Se implementarmos os algoritmos em diferentes ambientes (implementações distintas, linguagens distintas, sistemas operacionais distintos, computadores distintos), é possível evidenciar o comportamento assimptótico semelhante?
    - De que forma se comportam diferentes algoritmos para o mesmo problema podem ser comparados?

(Retirado do documento disponibilizado pelo professor)
@Francimary Publiquei isso aqui para poder testar o ambiente e ver o que tem de funcionalidade.

**Comment by Francimary** [comment]
Certo!

Em 14 de março de 2017 10:47, flavio-carvalho <notifications@github.com>
escreveu:

**Comment by AdalbertoAndrade** [comment]
Podemos testar o mesmo algoritmo em máquinas diferentes e desenvolver uma análise dentro dos resultados diferentes obtidos. Posso rodar em 3 servidores diferentes no meu trabalho.
Adalberto
