### ISSUE TITLE
Produtos Entregáveis

### ISSUE THREAD

**Issue by flavio-carvalho** [Francimary/Algoritmos#2]
## Relatório resultados. 
Deve ser apresentado um relatório técnico de pesquisa contendo todos os resultados alcançados no projeto. Uma estruturação de referência para o relatório técnico é a seguinte:
    - Introdução (apresentação e motivação do problema, histórico etc.)
    - Literatura / referências / trabalhos relacionados (tanto para o problema, quanto para os algoritmos, quanto para os métodos de análise)
    - Algoritmos (descrição do funcionamento dos algoritmos a serem analisados)
    - Análise teórica dos algoritmos
    - Análise experimental dos algoritmos (com descrição do ambiente/metodologia)
    - Resultados experimentais.

## Relatório de projeto. 
Devem ser apresentados todos os artefatos gerados ao longo do projeto, incluindo:
-  artefatos de gestão (cronogramas, atas de reunião etc.) 
-  artefatos de engenharia (especificação de requisitos, modelos de dados, códigos-fonte, planos de teste etc.). 

O aluno/grupo deve apresentar um relatório (5 a 10 páginas) que descreva como foi desenvolvido e organizado o projeto.

**Comment by flavio-carvalho** [comment]
Sobre o relatório do projeto, alguém se habilita a criar um cronograma? Acho interessante, sendo que quanto mais detalhado por tarefas, mais fácil para depois separarmos as atividades que cada um pode fazer de acordo com a habilidade e preferência pessoal. 
Acredito que não temos atas de reunião. Alguma ideia de algo parecido (acho que não precisamos de algo tão formal...)
Quanto à parte de artefatos de engenharia, tirado código fontes, não sei como produzir.

**Comment by Francimary** [comment]
Eu faço o cronograma que sugeriste, é bom para mantermos os prazos e a divisão de responsáveis.
agora que notei a necessidade das especificações, vamos montar!

**Comment by Francimary** [comment]
Ah, você que está sugerindo as especificações... fiquei na dúvida se essa documentação é assim tão importante nesse contexto Flavio!
Acredito que precisamos nos aprofundar mais nas diferentes abordagens para resolver o problema de Ordenação, já que fechamos nesse item.
Por exemplo, será que não seria interessante montar uma solução recursiva para entender como se comporta nesse tipo de problema, comparando com a solução iterativa?
Interessante discorrer também sobre cada uma das abordagens utilizadas tentando mostrar com o caso prático quando é interessante ou não o uso.

**Comment by Francimary** [comment]
@flavio-carvalho  mudei de ideia em relação aos artefatos, por que o professor sugeriu de fato as especificações. Vou incluir no cronograma.
