### ISSUE TITLE
Consulta a sugestão de melhoria: escolher "range" e "tamanho da lista"?

### ISSUE THREAD

**Issue by flavio-carvalho** [Francimary/Algoritmos#3]
Vocês acham que devemos facilitar a escolha do tamanho e range da lista, criando um prompt para consulta do usuário, ao invés de modificarmos no próprio código toda vez que quisermos alterar?

**Comment by Francimary** [comment]
OI Flavio,  é uma ideia para deixar o código mais interativo, é uma boa sim, eu gosto disso, fica mais amigável e não acredito que vá representar um peso de processamento que faça diferença no tempo
